---
- name:  실시간 에러 감지 및 LightSpeed 조치방안 수
  hosts: all
  sources:
    - ansible.eda.tail:
        path: /var/log/messages
        # 앤서블 자체 로그에 반응하지 않도록 필터링이 필요할 수 있습니다.
  rules:
  - name: 모든 시스템 에러 감지
    condition: event.line search("error|fail|critical|panic", ignorecase=true)
    action:
      run_playbook:
        name: "ai_analyze_and_fix.yml"
        extra_vars:
          raw_log: "{{ event.line }}"
