- name: OOM Monitor Rulebook
  hosts: all
  sources:
    - ansible.eda.file_watch:
        paths:
          - /var/log/messages

  rules:
    - name: Detect OOM and Trigger SOSReport
      condition: event.info is search("Out of memory", ignorecase=true)
      action:
        run_job_template:
          name: "Collect-SOSReport" # AAP에 등록할 템플릿 이름과 똑같아야 합니다.
